### ISSUE TITLE
テストに失敗する件について

### ISSUE THREAD

**Issue by mizushima1226** [yiinuma/next-storybook-start#3]
ローカルでテストを実行してみたところ失敗するようです
以下、`yarn test`の実行結果ですがお手元の環境で再現しますでしょうか？

<details>
<summary>実行結果</summary>
```
FAIL  src/components/TaskList.test.tsx
  Storyshots
    Task
      ✕ Default (7 ms)
      ✕ Pinned (1 ms)
      ✕ Archived (1 ms)
      ✓ Long Title (1 ms)
    TaskList
      ✕ Default Tasks (3 ms)
      ✕ With Pinned Tasks (2 ms)
      ✓ Loading (1 ms)
      ✕ Empty (1 ms)
  TaskList Test
    ✓ renders pinned tasks at the start of the list (16 ms)

  ● Storyshots › Task › Default

    expect(received).toMatchSnapshot()

    Snapshot name: `Storyshots Task Default 1`

    - Snapshot  - 0
    + Received  + 5

    @@ -19,10 +19,15 @@
          className="title"
        >
          <input
            placeholder="Input title"
            readOnly={true}
    +       style={
    +         Object {
    +           "textOverflow": "ellipsis",
    +         }
    +       }
            type="text"
            value="OK Test Task"
          />
        </div>
        <div

      at match (node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:25:32)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:34:16
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:47:20)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:317:13)
      at runJest (node_modules/@jest/core/build/runJest.js:407:19)

  ● Storyshots › Task › Pinned

    expect(received).toMatchSnapshot()

    Snapshot name: `Storyshots Task Pinned 1`

    - Snapshot  - 0
    + Received  + 5

    @@ -19,10 +19,15 @@
          className="title"
        >
          <input
            placeholder="Input title"
            readOnly={true}
    +       style={
    +         Object {
    +           "textOverflow": "ellipsis",
    +         }
    +       }
            type="text"
            value="OK Test Task"
          />
        </div>
        <div

      at match (node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:25:32)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:34:16
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:47:20)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:317:13)
      at runJest (node_modules/@jest/core/build/runJest.js:407:19)

  ● Storyshots › Task › Archived

    expect(received).toMatchSnapshot()

    Snapshot name: `Storyshots Task Archived 1`

    - Snapshot  - 0
    + Received  + 5

    @@ -19,10 +19,15 @@
          className="title"
        >
          <input
            placeholder="Input title"
            readOnly={true}
    +       style={
    +         Object {
    +           "textOverflow": "ellipsis",
    +         }
    +       }
            type="text"
            value="OK Test Task"
          />
        </div>
        <div

      at match (node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:25:32)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:34:16
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:47:20)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:317:13)
      at runJest (node_modules/@jest/core/build/runJest.js:407:19)

  ● Storyshots › TaskList › Default Tasks

    expect(received).toMatchSnapshot()

    Snapshot name: `Storyshots TaskList Default Tasks 1`

    - Snapshot  -  0
    + Received  + 30

    @@ -29,10 +29,15 @@
              className="title"
            >
              <input
                placeholder="Input title"
                readOnly={true}
    +           style={
    +             Object {
    +               "textOverflow": "ellipsis",
    +             }
    +           }
                type="text"
                value="Task 1"
              />
            </div>
            <div
    @@ -69,10 +74,15 @@
              className="title"
            >
              <input
                placeholder="Input title"
                readOnly={true}
    +           style={
    +             Object {
    +               "textOverflow": "ellipsis",
    +             }
    +           }
                type="text"
                value="Task 2"
              />
            </div>
            <div
    @@ -109,10 +119,15 @@
              className="title"
            >
              <input
                placeholder="Input title"
                readOnly={true}
    +           style={
    +             Object {
    +               "textOverflow": "ellipsis",
    +             }
    +           }
                type="text"
                value="Task 3"
              />
            </div>
            <div
    @@ -149,10 +164,15 @@
              className="title"
            >
              <input
                placeholder="Input title"
                readOnly={true}
    +           style={
    +             Object {
    +               "textOverflow": "ellipsis",
    +             }
    +           }
                type="text"
                value="Task 4"
              />
            </div>
            <div
    @@ -189,10 +209,15 @@
              className="title"
            >
              <input
                placeholder="Input title"
                readOnly={true}
    +           style={
    +             Object {
    +               "textOverflow": "ellipsis",
    +             }
    +           }
                type="text"
                value="Task 5"
              />
            </div>
            <div
    @@ -229,10 +254,15 @@
              className="title"
            >
              <input
                placeholder="Input title"
                readOnly={true}
    +           style={
    +             Object {
    +               "textOverflow": "ellipsis",
    +             }
    +           }
                type="text"
                value="Task 6"
              />
            </div>
            <div

      at match (node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:25:32)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:34:16
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:47:20)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:317:13)
      at runJest (node_modules/@jest/core/build/runJest.js:407:19)

  ● Storyshots › TaskList › With Pinned Tasks

    expect(received).toMatchSnapshot()

    Snapshot name: `Storyshots TaskList With Pinned Tasks 1`

    - Snapshot  -  0
    + Received  + 30

    @@ -29,10 +29,15 @@
              className="title"
            >
              <input
                placeholder="Input title"
                readOnly={true}
    +           style={
    +             Object {
    +               "textOverflow": "ellipsis",
    +             }
    +           }
                type="text"
                value="Task 6 (pinned)"
              />
            </div>
            <div
    @@ -69,10 +74,15 @@
              className="title"
            >
              <input
                placeholder="Input title"
                readOnly={true}
    +           style={
    +             Object {
    +               "textOverflow": "ellipsis",
    +             }
    +           }
                type="text"
                value="Task 1"
              />
            </div>
            <div
    @@ -109,10 +119,15 @@
              className="title"
            >
              <input
                placeholder="Input title"
                readOnly={true}
    +           style={
    +             Object {
    +               "textOverflow": "ellipsis",
    +             }
    +           }
                type="text"
                value="Task 2"
              />
            </div>
            <div
    @@ -149,10 +164,15 @@
              className="title"
            >
              <input
                placeholder="Input title"
                readOnly={true}
    +           style={
    +             Object {
    +               "textOverflow": "ellipsis",
    +             }
    +           }
                type="text"
                value="Task 3"
              />
            </div>
            <div
    @@ -189,10 +209,15 @@
              className="title"
            >
              <input
                placeholder="Input title"
                readOnly={true}
    +           style={
    +             Object {
    +               "textOverflow": "ellipsis",
    +             }
    +           }
                type="text"
                value="Task 4"
              />
            </div>
            <div
    @@ -229,10 +254,15 @@
              className="title"
            >
              <input
                placeholder="Input title"
                readOnly={true}
    +           style={
    +             Object {
    +               "textOverflow": "ellipsis",
    +             }
    +           }
                type="text"
                value="Task 5"
              />
            </div>
            <div

      at match (node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:25:32)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:34:16
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:47:20)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:317:13)
      at runJest (node_modules/@jest/core/build/runJest.js:407:19)

  ● Storyshots › TaskList › Empty

    expect(received).toMatchSnapshot()

    Snapshot name: `Storyshots TaskList Empty 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -15,11 +15,11 @@
              className="icon-check"
            />
            <div
              className="title-message"
            >
    -         You have no tasks
    +         You have no tasks!
            </div>
            <div
              className="subtitle-message"
            >
              Sit back and relax

      at match (node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:25:32)
      at node_modules/@storybook/addon-storyshots/dist/ts3.9/test-bodies.js:34:16
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/ts3.9/api/snapshotsTestsTemplate.js:47:20)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:317:13)
      at runJest (node_modules/@jest/core/build/runJest.js:407:19)

 › 6 snapshots failed.
Snapshot Summary
 › 6 snapshots failed from 1 test suite. Inspect your code changes or press `u` to update them.
 › 1 snapshot file obsolete from 1 test suite. To remove it, press `u`.
   ↳   • src/__snapshots__/storybook.test.ts.snap

Test Suites: 1 failed, 1 total
Tests:       6 failed, 3 passed, 9 total
Snapshots:   6 failed, 1 file obsolete, 2 passed, 8 total
Time:        0.519 s, estimated 1 s
Ran all test suites.
```
</details>

**Comment by yiinuma** [comment]
snapshotoをu押下で更新したらエラーがクリアされました
